local_backend: true

backend:
  name: git-gateway
  branch: add-cms

media_folder: "WEB/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "About Pages"
    files:
      - name: "contact"
        label: "Contact Information"
        file: "WEB/about/contact.markdown"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "Contact Us"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/contact-us"}
          - {label: "Body content", name: "body", widget: "markdown"}
      - name: "facilities"
        label: "Facilities Page"
        file:  "WEB/about/facilities.markdown"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "Facilities"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/facilities"}
          - {label: "Body content", name: "body", widget: "markdown"}
  - name: "research"
    label: "Create Research Post"
    folder: "WEB/POSTS/research/_posts"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body content", name: "body", widget: "markdown"}

  - name: "news"
    label: "News Announcements"
    folder: "WEB/POSTS/news/_posts"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body content", name: "body", widget: "markdown"}
  - name: "events"
    label: "Create Events"
    folder: "WEB/POSTS/events/_posts"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body content", name: "body", widget: "markdown"}
         
  - name: "schedules"
    label: "Course Schedules"
    media_folder: "WEB/assets/schedules"
    public_folder: "/WEB/assets/schedules"
    files:
      - name: "schedule_list"
        label: "Manage Schedules"
        file: "_data/schedules.yml"
        fields:
          - label: "Semesters"
            name: "items"
            add_to_top: true
            widget: "list"
            fields:
              - {label: "Semester Name", name: "semester", widget: "string", hint: "e.g. Spring 2026"}
              - {label: "Schedule Excel File", name: "schedule_file", widget: "file"}